name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.4.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    container: cypress/base:3.1.3 
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
